// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkEJrv0IyBNARUfonqM3mJtA3LnXlohsA',
    appId: '1:888953774658:web:6895d560ad1f5da81a03db',
    messagingSenderId: '888953774658',
    projectId: 'stepforward-b4fba',
    authDomain: 'stepforward-b4fba.firebaseapp.com',
    storageBucket: 'stepforward-b4fba.firebasestorage.app',
    measurementId: 'G-684JPTCDBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByxxcc9HwM7GzsQnByo1AP0S6lkyOf2rU',
    appId: '1:888953774658:android:6bd51949e10f6ee51a03db',
    messagingSenderId: '888953774658',
    projectId: 'stepforward-b4fba',
    storageBucket: 'stepforward-b4fba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2PS-dDMuHyWojL9xBR-kk4XbNH_EAEpY',
    appId: '1:888953774658:ios:cb1c5e79dce972da1a03db',
    messagingSenderId: '888953774658',
    projectId: 'stepforward-b4fba',
    storageBucket: 'stepforward-b4fba.firebasestorage.app',
    iosBundleId: 'com.example.stepforward',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2PS-dDMuHyWojL9xBR-kk4XbNH_EAEpY',
    appId: '1:888953774658:ios:cb1c5e79dce972da1a03db',
    messagingSenderId: '888953774658',
    projectId: 'stepforward-b4fba',
    storageBucket: 'stepforward-b4fba.firebasestorage.app',
    iosBundleId: 'com.example.stepforward',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHzBUudkCGKJbtRZC4FExs7GkZsvlTzP4',
    appId: '1:888953774658:web:2d3d0f83a7e89df91a03db',
    messagingSenderId: '888953774658',
    projectId: 'stepforward-b4fba',
    authDomain: 'stepforward-b4fba.firebaseapp.com',
    storageBucket: 'stepforward-b4fba.firebasestorage.app',
    measurementId: 'G-CHE89DH262',
  );
}
